### ISSUE TITLE
SnapStart infrequent spikes in duration

### ISSUE THREAD

**Issue by HasseNasse** [aws/aws-lambda-snapstart-java-rules#9]
Please have a read here of some tests that were made with SnapStart.
https://github.com/hreem-it/case-studies/tree/master/native-vs-snapstart

**Comment by valerena** [comment]
Hi. Your results are not related with the SnapStart bug scanner hosted in this repository, but with the SnapStart feature itself. We recommend you to share your results and/or ask questions on https://repost.aws or directly with AWS Support.
